apiVersion: v1
kind: ConfigMap
metadata:
  name: php-index
  namespace: lab4
data:
  index.php: |
    <?php
    $mysqli = new mysqli(
      getenv('DB_HOST'),
      getenv('DB_USER'),
      getenv('DB_PASS')
    );

    if ($mysqli->connect_error) {
      die('❌ Ошибка подключения (' . $mysqli->connect_errno . ') ' . $mysqli->connect_error);
    } else {
      echo "✅ Успешное подключение к MySQL!";
    }
    ?>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: lab4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: web
        image: richarvey/nginx-php-fpm:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
        - name: php-code
          mountPath: /var/www/html
      volumes:
      - name: php-code
        configMap:
          name: php-index
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: lab4
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: lab4
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: lab4
type: Opaque
data:
  password: VHVzdXIxMjMh
---
apiVersion: v1
kind: Namespace
metadata: 
  name: lab4
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-database
  namespace: lab4
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
